### ISSUE TITLE
abserv: When using a skill on a target that is out of range go to this target then use the skill

### ISSUE THREAD

**Issue by stievie** [stievie/ABx#14]
NPCs with an AI do it, but players should also do it.

**Comment by pablokawan** [comment]
maybe you can do like i did with interaction in my fork, but idk how will works 'cause when follow the target, he steps into the last position of the npc

**Comment by stievie** [comment]
Hm, you mean let the client move to the target. This is an interesting idea, and may make this much simpler.

Oh, btw. if you have some interesting changes you want to be merged into this, you can make a pull request. Just make sure you have a separate branch with the changes you want to be merged, otherwise the PW will contain all your changes.

**Comment by pablokawan** [comment]
Okay, thank you, its the first time that im using github, im learning

**Comment by stievie** [comment]
No problem, I'm also just a git commit/push/pull only guy :D. Anyway I wrote here https://github.com/stievie/ABx/blob/master/CONTRIBUTING.md#pull-requests something about that.

I'm Austrian so also not an english native speaker.
