### ISSUE TITLE
abserv: Crash

### ISSUE THREAD

**Issue by stievie** [stievie/ABx#52]
![Clipboard01](https://user-images.githubusercontent.com/900888/88146030-a09b8d00-cbfb-11ea-9b56-ce5952d70255.png)

**Comment by igorsegallafa** [comment]
There is some place where I can get the updated client? The client is crashing when I create a character, I believe that is missing some file on client.

**Comment by stievie** [comment]
This issue is about a server crash. I think you issue is something different. Please make a new Issue with a description where/why/how it crashes.
The client is in the source tree, you must compile it.

**Comment by stievie** [comment]
Didn't see this crash anymore.
