### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ComputeAngleBone** [stievie/ABx#54]
Ok, after i re-install again, and check step by step, 
I got all servers running.
I can Create Account and Create Character using fwclient-win64 from GDrive
but after create character i got  some console errors about E/A
But my problem now is when i use my own build fw client, is crashing when click on Login or Create Account.. 
i started debugging and got a breakpoint on 
`LoginLevel::SetEnvironment() ->  
unsigned selEnv = environmentsList_->GetSelection();`
Exception thrown at 0x00007FF6602AC680 in fw.exe: 0xC0000005: Access violation reading location 0x00000000000002D8.

environmentsList_ is null.

**Comment by stievie** [comment]
Thank you, this is may bad :D. I fixed it. Can you pull and rebuild the client please.
