### ISSUE TITLE
Invisible Player

### ISSUE THREAD

**Issue by ComputeAngleBone** [stievie/ABx#55]
![image](https://user-images.githubusercontent.com/39961856/89094749-cb28db00-d39d-11ea-9f27-6380a6fa3996.png)

**Comment by stievie** [comment]
Oh yeah, I noticed that before, Urho3D devs seem to have deleted some Techniques I use. We can either fix all Materials or you can copy the attached techniques to `abclient\bin\CoreData`.

[Techniques.zip](https://github.com/stievie/ABx/files/5009885/Techniques.zip)
