### ISSUE TITLE
Game Settings - Texture Quality

### ISSUE THREAD

**Issue by ComputeAngleBone** [stievie/ABx#58]
when down quality the sprites seems to works on tile mode
![image](https://user-images.githubusercontent.com/39961856/89095027-383d7000-d3a0-11ea-9504-a62f667d82f8.png)

**Comment by stievie** [comment]
Oh, that looks awesome, lol no. I'll look into it, thanks for reporting.

**Comment by stievie** [comment]
Finally found the problem: https://github.com/urho3d/Urho3D/issues/2351 UI textures sould ignore quality settings.

So either add a XML file for UI Texture
~~~xml
<texture>
    <mipmap enable="false" />
    <quality low="0" />
</texture>
~~~

or set it in code:

~~~cpp
texture->SetNumLevels(1);
texture->SetMipsToSkip(QUALITY_LOW, 0);
~~~
