### ISSUE TITLE
D3D9 Link

### ISSUE THREAD

**Issue by ComputeAngleBone** [stievie/ABx#61]
Oh, i forgot to say.

when i try to build abclient.. so i added d3d9.lib to input and everything works fine.

1>------ Build started: Project: abclient, Configuration: Release x64 ------
1>   Creating library Release/abclient.lib and object Release/abclient.exp
1>Urho3D.lib(D3D9Graphics.obj) : error LNK2001: unresolved external symbol Direct3DCreate9

**Comment by stievie** [comment]
Oh, right, I mentioned this now in BUILD.md. I never did a really clean build on Windows :D.

Maybe you should also build Urho3D for D3D11, see BUILD.md how to do that. You can verify that when you hit F12 in the client.
