### ISSUE TITLE
Client Connection Status

### ISSUE THREAD

**Issue by ComputeAngleBone** [stievie/ABx#62]
Maybe a feature, add server connection status in login screen.
Like Online/Offline

**Comment by stievie** [comment]
This is an interesting one. I don't know how other game server do that. I think one way would be to send some UDP packet to the login server, and the client can see then what or anything comes back. This would also avoid all TCP connection overhead.

I'll have to investigate this, but i think this would be a great addition.

**Comment by stievie** [comment]
Maybe something like this https://github.com/farnyser/cpp-ping-pong/blob/master/src/udp.cpp

**Comment by stievie** [comment]
Oh I love that!

Without environments:
![image](https://user-images.githubusercontent.com/900888/89174634-7e542880-d586-11ea-95fc-a914eb452fbf.png)

With environments:
![image](https://user-images.githubusercontent.com/900888/89174745-a3489b80-d586-11ea-9514-e37b9eb978a4.png)
