### ISSUE TITLE
Zoom Crashes

### ISSUE THREAD

**Issue by pablokawan** [stievie/ABx#63]
maybe needs some adjustment on maximum and minimum zoom, if zoom really close to the player will cause a normalize crash

**Comment by stievie** [comment]
Hm, this is interesting, because actually you should be able to zoom until you are in first person perspective. Thanks for reporting, I'll investigate it.

**Comment by stievie** [comment]
I can't reproduce that. Is it possible for you to run in in the Debugger and see where it crashes?

**Comment by pablokawan** [comment]
![image](https://user-images.githubusercontent.com/52059799/89323086-9b0e6000-d65b-11ea-98d9-a877ebc23eca.png)
Steps : Just log-in character and zoom inside the back of the head

**Comment by stievie** [comment]
Oh we are doing a ray cast with a direction vector 0, this can't work :D. Thank you, I fixed it.
