### ISSUE TITLE
FPS Optimization

### ISSUE THREAD

**Issue by pablokawan** [stievie/ABx#64]
i know maybe isnt your focus right now but, what we can do about the fps?
im running with a i9-9900k and got only 27/30 fps on Athena, 57/64+ on Spartha D=

**Comment by stievie** [comment]
At the moment the models and textures are very unoptimized, especially the human models have way too many polygons. For now you can try to turn off shadows (Options -> Graphics), since thats the most heavy. I can't run 2 instances of the client when shadows are on with a GeForce 970.

**Comment by pablokawan** [comment]
Oh, i found the problem, if minimap is on the fps goes down, if i disable him got 200++ fps

**Comment by stievie** [comment]
Yeah, the minimap is a bit of a pain point. It doesn't work at all as it is now. I think I need to find a totally different solution. For example making a 2D map of each Scene and drawing that instead. I think this is how other games do it.
