### ISSUE TITLE
Better head tracking

### ISSUE THREAD

**Issue by pablokawan** [stievie/ABx#67]
Hmm, while using PLAYER_HEAD_ANIMATION you cant look for yourself directly,
When aim to de head the player get shy and always look to the sides.

I see that we have some wall camera collision, maybe can add something like to the ground too ? to avoid the x-ray world

**Comment by stievie** [comment]
Ok, I fixed that, didn't play with the PLAYER_HEAD_ANIMATION for a long time, but it looks cute.

The camera actually should collide with the terrain as well, but like so much other code, also this is a bit weak :/.

**Comment by pablokawan** [comment]
Awesome!!

**Comment by pablokawan** [comment]
Theres a way to make like the modern mmos, the player aways look to de camera when when the camera is in from of the player?
thats better to see the character, but u did a great job, some interpolation can be good too in production.

**Comment by stievie** [comment]
Okay, that was easy :D.

Also fixed terrain collision with the camera.
