### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pablokawan** [stievie/ABx#68]
Hmm, how to works the `click -> look to player` of the game?
i see on abclient how to works the npc name click hook but how is the game handling the actor click and the rotate?
can you breakpoint the lines for me ?

**Comment by stievie** [comment]
This is done by the server. 
1. The client only sends a CickObject mesage to the server (https://github.com/stievie/ABx/blob/master/abclient/abclient/Player.cpp#L454), 
2. the server forwards it to the Lua script of the NPC (e.g. for the Merchant https://github.com/stievie/ABx/blob/master/bin/data/scripts/actors/npcs/merchant.lua#L62) 
3. which calls the `void Actor::FaceObject(GameObject* object)` function in https://github.com/stievie/ABx/blob/master/abserv/abserv/Actor.cpp#L657
4. which calls `void MoveComp::HeadTo(const Math::Vector3& pos)` https://github.com/stievie/ABx/blob/master/abserv/abserv/MoveComp.cpp#L90

I hope this helps.

**Comment by pablokawan** [comment]
how i can detect if the object
`GameObject* object = GetObjectAt<GameObject>(input->GetMousePosition());`
is the actual player ?

**Comment by stievie** [comment]
You can use Player as template argument: `GetObjectAt<Player>`. If it's not a player it returns `nullptr`. Or you can use `Is<Player>(object)` returns true when its a player.

**Comment by stievie** [comment]
Oh you were on IRC, sorry I was paint a wall.
