### ISSUE TITLE
Camera bug

### ISSUE THREAD

**Issue by pablokawan** [stievie/ABx#69]
![image](https://user-images.githubusercontent.com/52059799/89375960-34259100-d6c5-11ea-98d5-adbbe221db27.png)
after latest merge when walking is doing a zoom to the player face

**Comment by pablokawan** [comment]
the reason is the commit c810924824de030ab9737418410ed7bb10f91a24

**Comment by stievie** [comment]
The players model should be hidden when the camera is too close. When you change in `Player::PostUpdate()`:
~~~cpp
    if (cameraDistance_ <= 0.2f)
        model_->SetViewMask(0);
    else if (model_->GetViewMask() == 0)
        model_->SetViewMask(static_cast<unsigned>(-1));
~~~
to:
~~~cpp
    if (cameraDistance_ <= 0.3f)
    {
        // Hide Player model in 1st person perspective
        model_->SetViewMask(0);
        rayDistance = 0;
    }
    else if (model_->GetViewMask() == 0)
        model_->SetViewMask(static_cast<unsigned>(-1));
~~~

does it fix it? Or is it fixed when you increase the threshold in `if (cameraDistance_ <= 0.3f)`?

**Comment by pablokawan** [comment]
oh, if uncheck the stick camera to the player head solve the problem, let me test your fix

**Comment by pablokawan** [comment]
its better now without conflict, but when walk still not in first person idk if thats ur point.
![image](https://user-images.githubusercontent.com/52059799/89388798-e4ea5b00-d6da-11ea-80ed-5c0474a3db14.png)
