### ISSUE TITLE
GCC compiler exit.

### ISSUE THREAD

**Issue by 0xdream** [stievie/ABx#76]
when I compiler this game with on ubuntu 20.04, 

I get this : 
`
/home/chunfeng/ABX/Include/pgsql/sched.h:70:3: error: #error Please upgrade your GNU compiler to one that supports __declspec.
   70 | # error Please upgrade your GNU compiler to one that supports __declspec.
      |   ^~~~~
`

`/home/chunfeng/ABX/Include/pgsql/sched.h:151:1: error: expected constructor, destructor, or type conversion before ‘(’ token
  151 | PTW32_DLLPORT int __cdecl sched_yield (void);
`

`/home/chunfeng/ABX/Include/pgsql/pthread.h:320:8: error: redefinition of ‘struct timespec’
`

`/home/chunfeng/ABX/Include/pgsql/pthread.h:736:29: error: expected ‘)’ before ‘ptw32_cleanup_callback_t’
  736 | typedef void (* PTW32_CDECL ptw32_cleanup_callback_t)(void *);
      |              ~              ^~~~~~~~~~~~~~~~~~~~~~~~
/home/chunfeng/ABX/Include/pgsql/pthread.h:744:3: error: ‘ptw32_cleanup_callback_t’ does not name a type
  744 |   ptw32_cleanup_callback_t routine;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
/home/chunfeng/ABX/Include/pgsql/pthread.h:891:1: error: expected constructor, destructor, or type conversion before ‘(’ token
  891 | PTW32_DLLPORT int PTW32_CDECL pthread_attr_init (pthread_attr_t * attr);
`

it seems something only used on windows platform, and how I to restrict it.

**Comment by 0xdream** [comment]
Then I try to compile with clion, some information I get : 

`Cannot get compiler information:
	Compiler exited with error code 1: /usr/bin/c++ -xc++ -DASIO_STANDALONE -DSA_ASSERT -DUSE_PGSQL -DWRITE_MINIBUMP -I/home/chunfeng/ABX/Include -I/home/chunfeng/ABX/ThirdParty/EASTL/test/packages/EABase/include/Common -I/home/chunfeng/ABX/Include/pgsql -I/home/chunfeng/ABX/abdb -I/home/chunfeng/ABX/abscommon -I/usr/include/lua5.3 -Wall -Wextra -march=native -fdiagnostics-color=always -fuse-ld=gold -Wno-maybe-uninitialized -g -fno-exceptions -fno-rtti -std=c++17 -Winvalid-pch -include /home/chunfeng/ABX/cmake-build-debug/abdb/CMakeFiles/abdb.dir/cmake_pch.hxx -fpch-preprocess -v -dD -E
	Using built-in specs.
	COLLECT_GCC=/usr/bin/c++
	OFFLOAD_TARGET_NAMES=nvptx-none:hsa
	OFFLOAD_TARGET_DEFAULT=1
	Target: x86_64-linux-gnu
	Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
	Thread model: posix
	gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
`

But I have the latest compiler, what is happen?

**Comment by stievie** [comment]
Yes, the Postgres headers should only be used on windows. Did run CMake without errors? I think on Ubuntu you also need `postgresql-server-dev-all` package so CMake can find Postgres, see https://github.com/stievie/ABx/blob/master/BUILD.md#install-gcc-and-dependencies-on-ubuntu.

See https://github.com/stievie/ABx/blob/master/.github/workflows/codeql-analysis.yml#L49 how to build it on a clean Ubuntu.

**Comment by 0xdream** [comment]
It's amazing when I install the postgresql-server-dev-all , it worked! thanks very much.

**Comment by 0xdream** [comment]
`I didn't try any other database backend than PostgreSQL since some time, so the others may or may not work.`

sorry for my bad english, I misunderstand you means, I mistaking the project not use PostgreSql as default db, so, I haven't to check the problem about postgresql.
